use_frameworks!  
platform :ios, '11.0'

target 'seniorProject' do
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Twitter'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/Twitter'
  pod 'FirebaseUI/Phone'

  #-----Google-----#
  pod 'GoogleSignIn'
  
  #-----Facebook-----#
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  #-----DropDown-----#
  pod 'UIDropDown'
  
end
